### ISSUE TITLE
no support for StorageServiceMBean.getRangeToEndpointMap 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-jmx#36]
We are missing support for this method

Some third party rely on it such as cassandra-reaper

**Comment by austinhallock** [comment]
Can confirm. https://github.com/scylladb/scylla/wiki/3rd-party-utilities should probably be updated to have cassandra-reaper under 'known to not work' instead of 'should work'. It starts up, but isn't able to run repairs without support for [getRangeToEndpointMap](https://github.com/scylladb/scylla/blob/master/api/storage_service.cc#L143)

**Comment by penberg** [comment]
@austinhallock Thanks for testing. I update the wiki page. /cc @tzach

**Comment by tfendt** [comment]
Any update on this? We are looking to transition from cassandra to scylla and currently use reaper for automated repairs on keyspaces.

**Comment by tomer-sandler** [comment]
@tfendt Scylla has automated repairs via [Scylla Manager](https://www.scylladb.com/product/scylla-manager/) (part of the enterprise version).
You can also set a chron job to trigger it every X days...

**Comment by dorlaor** [comment]
@amnonh folks who use Janus Graph needs it and they rather not use Scylla Manager, how hard would it be to fix it?

**Comment by rmb938** [comment]
I am also having an issue since some jmx api's aren't supported and cassandra reaper cant function.

Scylla Manager isn't an option for my deployments since my clusters are more than 5 nodes.
